server:
  port: 80

spring:
  security:
    oauth2:
      authorizationserver:
#        issuer-url: https://simpleauthserver.onrender.com
        issuer-url: http://auth-server
#        issuer-url: http://127.0.0.1:9000
        # Client setup
        client:
          io-portal:
            registration:
              client-id: io-portal
              client-secret: "{noop}secret"
              client-name: ioportal
              client-authentication-methods:
                - client_secret_basic
              authorization-grant-types:
                - authorization_code
                - refresh_token
              redirect-uris:
                - http://localhost:8080/login/oauth2/code/ioportal
#                - http://127.0.0.1:8080/authorized
              scopes:
                - openid
                - user
        endpoint:
          token-uri: http://auth-server/access_token

logging:
  level:
    org:
      springframework:
        security: trace

